"""Turbulent premixed-flame regime helpers and plotting.

The regime placement provided here is based on the classical Borghi/Peters-style
interpretation using:

- x-axis: l_t / delta_L
- y-axis: u' / S_L

The implementation also reports the commonly used derived numbers:

- Damkohler number: Da = (l_t / u') / (delta_L / S_L)
- Karlovitz number: Ka ~ (u'/S_L)^(3/2) (l_t/delta_L)^(-1/2)

For this package, the default thickness used in the regime calculations is the thermal
-diffusivity thickness `delta_alpha = alpha_u / S_L`.

Important
---------
These diagrams are classically defined for 3D turbulent premixed flames. When used with
2D HIT generated by NS2dLab, the placement should be interpreted as an approximate,
qualitative classification tool rather than a strict 3D turbulence result.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np

from .flame_properties import FlameProperties
from .hit_stats import HITStats


@dataclass(slots=True)
class RegimePoint:
    """Dimensionless point used on a turbulent flame regime diagram."""

    uprime: float
    integral_length_scale: float
    S_L: float
    delta_L: float
    uprime_over_Sl: float
    lt_over_deltaL: float
    Da: float
    Ka: float
    thickness_definition: str


def compute_regime_point(
    hit: HITStats,
    flame: FlameProperties,
    *,
    uprime_definition: str = "component_rms",
    thickness_definition: str = "delta_alpha",
) -> RegimePoint:
    """Combine HIT and flame properties into regime-diagram coordinates."""
    if uprime_definition == "component_rms":
        uprime = hit.uprime_component_rms
    elif uprime_definition == "planar_rms":
        uprime = hit.uprime_planar_rms
    else:
        raise ValueError(f"Unknown uprime_definition: {uprime_definition}")

    if thickness_definition == "delta_alpha":
        delta_L = flame.delta_alpha
    elif thickness_definition == "delta_T":
        delta_L = flame.delta_T
    else:
        raise ValueError(f"Unknown thickness_definition: {thickness_definition}")

    lt = hit.integral_length_scale_mean
    uprime_over_Sl = float(uprime / flame.S_L)
    lt_over_deltaL = float(lt / delta_L)
    Da = float((lt * flame.S_L) / (uprime * delta_L))
    Ka = float((uprime_over_Sl ** 1.5) * (lt_over_deltaL ** -0.5))

    return RegimePoint(
        uprime=float(uprime),
        integral_length_scale=float(lt),
        S_L=float(flame.S_L),
        delta_L=float(delta_L),
        uprime_over_Sl=uprime_over_Sl,
        lt_over_deltaL=lt_over_deltaL,
        Da=Da,
        Ka=Ka,
        thickness_definition=thickness_definition,
    )


def regime_point_to_dict(point: RegimePoint) -> dict[str, Any]:
    return asdict(point)


def plot_borghi_peters_diagram(
    point: RegimePoint,
    *,
    output_path: str | Path,
    title: str = "Turbulent flame regime diagram",
    annotate: str | None = None,
) -> None:
    """Plot a simple Borghi/Peters-style diagram with the supplied case point.

    The region boundaries drawn here are heuristic guide lines based on the commonly used
    Da=1 and Ka=1 relations. They are intended to help users orient the case quickly.
    """
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    x = np.logspace(-1, 4, 400)
    da1 = x
    ka1 = x ** (1.0 / 3.0)
    ka100 = 100.0 ** (2.0 / 3.0) * x ** (1.0 / 3.0)

    fig, ax = plt.subplots(figsize=(8.5, 6.5))
    ax.loglog(x, da1, "k--", linewidth=1.0, label="Da = 1")
    ax.loglog(x, ka1, color="tab:gray", linestyle="-.", linewidth=1.0, label="Ka = 1")
    ax.loglog(x, ka100, color="tab:gray", linestyle=":", linewidth=1.0, label="Ka = 100")

    ax.scatter([point.lt_over_deltaL], [point.uprime_over_Sl], s=80, color="tab:red", zorder=5)
    if annotate is not None:
        ax.annotate(annotate, (point.lt_over_deltaL, point.uprime_over_Sl), xytext=(8, 8), textcoords="offset points")

    ax.text(0.18, 0.18, "Laminar / weakly perturbed", transform=ax.transAxes)
    ax.text(0.18, 0.55, "Wrinkled / corrugated flamelets", transform=ax.transAxes)
    ax.text(0.55, 0.68, "Thin reaction zones", transform=ax.transAxes)
    ax.text(0.72, 0.25, "Broken reaction zones / distributed", transform=ax.transAxes)

    ax.set_xlabel(r"$l_t / \delta_L$")
    ax.set_ylabel(r"$u' / S_L$")
    ax.set_title(title)
    ax.grid(True, which="both", alpha=0.25)
    ax.legend(loc="lower right")
    ax.set_xlim(1e-1, 1e4)
    ax.set_ylim(1e-2, 1e3)

    footer = (
        f"Point: u'/S_L={point.uprime_over_Sl:.3g}, l_t/delta_L={point.lt_over_deltaL:.3g}, "
        f"Da={point.Da:.3g}, Ka={point.Ka:.3g}"
    )
    fig.text(0.01, 0.01, footer)
    fig.tight_layout()
    fig.savefig(output, dpi=220)
    plt.close(fig)
