"""Turbulent premixed-flame regime helpers and plotting.

The regime placement provided here is based on the classical Borghi/Peters-style
interpretation using:

- x-axis: l_t / delta_L
- y-axis: u' / S_L

The implementation also reports the commonly used derived numbers:

- Damkohler number: Da = (l_t / u') / (delta_L / S_L)
- Karlovitz number: Ka ~ (u'/S_L)^(3/2) (l_t/delta_L)^(-1/2)

For this package, the default thickness used in the regime calculations is the thermal
-diffusivity thickness `delta_alpha = alpha_u / S_L`.

Important
---------
These diagrams are classically defined for 3D turbulent premixed flames. When used with
2D HIT generated by NS2dLab, the placement should be interpreted as an approximate,
qualitative classification tool rather than a strict 3D turbulence result.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np

from .flame_properties import FlameProperties
from .hit_stats import HITStats
from .plot_style import add_light_ygrid, apply_academic_plot_style, categorical_colors


@dataclass(slots=True)
class RegimePoint:
    """Dimensionless point used on a turbulent flame regime diagram."""

    uprime: float
    integral_length_scale: float
    S_L: float
    delta_L: float
    uprime_over_Sl: float
    lt_over_deltaL: float
    Da: float
    Ka: float
    thickness_definition: str


def compute_regime_point(
    hit: HITStats,
    flame: FlameProperties,
    *,
    uprime_definition: str = "component_rms",
    thickness_definition: str = "delta_alpha",
) -> RegimePoint:
    """Combine HIT and flame properties into regime-diagram coordinates."""
    if uprime_definition == "component_rms":
        uprime = hit.uprime_component_rms
    elif uprime_definition == "planar_rms":
        uprime = hit.uprime_planar_rms
    else:
        raise ValueError(f"Unknown uprime_definition: {uprime_definition}")

    if thickness_definition == "delta_alpha":
        delta_L = flame.delta_alpha
    elif thickness_definition == "delta_T":
        delta_L = flame.delta_T
    else:
        raise ValueError(f"Unknown thickness_definition: {thickness_definition}")

    lt = hit.integral_length_scale_mean
    uprime_over_Sl = float(uprime / flame.S_L)
    lt_over_deltaL = float(lt / delta_L)
    Da = float((lt * flame.S_L) / (uprime * delta_L))
    Ka = float((uprime_over_Sl ** 1.5) * (lt_over_deltaL ** -0.5))

    return RegimePoint(
        uprime=float(uprime),
        integral_length_scale=float(lt),
        S_L=float(flame.S_L),
        delta_L=float(delta_L),
        uprime_over_Sl=uprime_over_Sl,
        lt_over_deltaL=lt_over_deltaL,
        Da=Da,
        Ka=Ka,
        thickness_definition=thickness_definition,
    )


def regime_point_to_dict(point: RegimePoint) -> dict[str, Any]:
    return asdict(point)


def plot_borghi_peters_diagram(
    point: RegimePoint,
    *,
    output_path: str | Path,
    title: str = "Turbulent flame regime diagram",
    annotate: str | None = None,
) -> None:
    """Plot a Borghi/Peters-style diagram with common regime boundaries.

    The plotted guide lines are:

    - turbulent Reynolds number: Re_t = (u'/S_L) (l_t/delta_L) = 1
    - Damkohler number: D_a = 1
    - Karlovitz number: K_a = 1
    - Karlovitz number: K_a = 100

    In this convention, the `D_a = 1` and `K_a = 1` lines are clipped so they begin at
    `(l_t/delta_L, u'/S_L) = (1, 1)` and therefore do not extend into the laminar region.
    """
    apply_academic_plot_style()
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)

    x_full = np.logspace(-1, 4, 600)
    x_turb = np.logspace(0, 4, 500)

    re_t_1 = x_full ** -1.0
    uprime_sl_1 = np.ones_like(x_turb)
    da_1 = x_turb
    ka_1 = x_turb ** (1.0 / 3.0)
    ka_100 = 100.0 ** (2.0 / 3.0) * x_full ** (1.0 / 3.0)

    colors = categorical_colors(5)
    fig, ax = plt.subplots(figsize=(8.5, 6.5))
    ax.loglog(x_full, re_t_1, "-", linewidth=1.1, color=colors[0])
    ax.loglog(x_turb, uprime_sl_1, "-", linewidth=1.1, color=colors[1])
    ax.loglog(x_turb, da_1, "--", linewidth=1.1, color=colors[2])
    ax.loglog(x_turb, ka_1, linestyle="-.", linewidth=1.1, color=colors[3])
    ax.loglog(x_full, ka_100, linestyle=":", linewidth=1.4, color=colors[4])

    ax.scatter([point.lt_over_deltaL], [point.uprime_over_Sl], s=170, color="#303030", edgecolors="white", linewidths=0.9, zorder=6)
    if annotate is not None:
        ax.annotate(annotate, (point.lt_over_deltaL, point.uprime_over_Sl), xytext=(8, 8), textcoords="offset points")

    ax.text(0.10, 0.11, "Laminar / weakly perturbed", transform=ax.transAxes)
    ax.text(0.29, 0.28, "Wrinkled flamelets", transform=ax.transAxes)
    ax.text(0.28, 0.47, "Corrugated flamelets", transform=ax.transAxes)
    ax.text(0.60, 0.67, "Thin reaction zones", transform=ax.transAxes)
    ax.text(0.73, 0.83, "Broken reaction zones", transform=ax.transAxes)

    # Inline line labels instead of a legend.
    ax.text(2.0e-1, 7.0, r"$Re_t=(u'/S_L)(l_t/\delta_L)=1$", color=colors[0], rotation=-27)
    ax.text(2.4, 1.18, r"$u'/S_L=1$", color=colors[1], rotation=0)
    ax.text(2.5e1, 3.0e1, r"$D_a=1$", color=colors[2], rotation=27)
    ax.text(1.7, 2.2, r"$K_a=1$", color=colors[3], rotation=18)
    ax.text(8.0, 3.5e1, r"$K_a=100$", color=colors[4], rotation=18)

    ax.set_xlabel(r"$l_t / \delta_L$")
    ax.set_ylabel(r"$u' / S_L$")
    ax.set_title(title)
    add_light_ygrid(ax)
    ax.grid(True, which="major", axis="x", alpha=0.15)
    ax.set_xlim(1e-1, 1e4)
    ax.set_ylim(1e-2, 1e3)

    footer = (
        f"Point: u'/S_L={point.uprime_over_Sl:.3g}, l_t/delta_L={point.lt_over_deltaL:.3g}, "
        f"Da={point.Da:.3g}, Ka={point.Ka:.3g}"
    )
    fig.text(0.01, 0.01, footer)
    fig.tight_layout()
    fig.savefig(output, dpi=220)
    plt.close(fig)
